/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-2",
  aws_appsync_graphqlEndpoint:
    "https://vsj4bn2fs5fdfamdcz6p35fr4y.appsync-api.us-west-2.amazonaws.com/graphql",
  aws_appsync_region: "us-west-2",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "gcyieuc6pfhfzpvaq2jhlcmzbe",
};

export default awsmobile;
